Join between MTL_MATERIAL_TRANSACTIONS and PA_PROJECTS_ALL

FROM   MTL_MATERIAL_TRANSACTIONS  MMT
       ,PA_PROJECTS_ALL PPA
       ,PA_TASKS PT
       ,MTL_SYSTEM_ITEMS_B MSI
WHERE  MMT.SOURCE_PROJECT_ID=PPA.PROJECT_ID
AND    MMT.SOURCE_TASK_ID=PT.TASK_ID
AND    PPA.PROJECT_ID=PT.PROJECT_ID
AND    MSI.INVENTORY_ITEM_ID=MMT.INVENTORY_ITEM_ID
AND    MSI.ORGANIZATION_ID=MMT.ORGANIZATION_ID
--AND  MMT.PM_COST_COLLECTED IS NULL
--AND    PPA.SEGMENT1 BETWEEN DECODE(:PA_SEGMENT1,'ALL',PPA.SEGMENT1,:PA_SEGMENT1) AND DECODE(:PA_SEGMENT1_1,'ALL',PPA.SEGMENT1,:PA_SEGMENT1_1)
--AND    TRUNC(MMT.TRANSACTION_DATE) BETWEEN NVL(:P_FROM_DATE,TRUNC(MMT.TRANSACTION_DATE)) AND NVL(:P_TO_DATE,TRUNC(MMT.TRANSACTION_DATE))